"""ajout champs AIOT et Inspection

Revision ID: 13fdf8662819
Revises: ac6ad78d1708
Create Date: 2022-05-02 14:03:25.155060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fdf8662819'
down_revision = 'ac6ad78d1708'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aiots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ied', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('synthese', sa.Text(), nullable=True))

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contexte', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('themes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('themes')
        batch_op.drop_column('contexte')

    with op.batch_alter_table('aiots', schema=None) as batch_op: 
        batch_op.drop_column('aiots', 'synthese')
        batch_op.drop_column('aiots', 'ied')
        batch_op.drop_column('aiots', 'code')
    # ### end Alembic commands ###
