"""ajout champs AIOT et Inspection

Revision ID: 13fdf8662819
Revises: ac6ad78d1708
Create Date: 2022-05-02 14:03:25.155060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fdf8662819'
down_revision = '5ed69db40d55'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aiots', sa.Column('code', sa.String(length=255), nullable=True))
    op.add_column('aiots', sa.Column('ied', sa.Boolean(), nullable=True))
    op.add_column('aiots', sa.Column('synthese', sa.Text(), nullable=True))
    op.add_column('inspections', sa.Column('contexte', sa.Text(), nullable=True))
    op.add_column('inspections', sa.Column('themes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'inspections', 'users', ['approbateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['verificateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['redacteur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'themes')
    op.drop_column('inspections', 'contexte')
    op.drop_column('aiots', 'synthese')
    op.drop_column('aiots', 'ied')
    op.drop_column('aiots', 'code')
    # ### end Alembic commands ###
