"""rev6

Revision ID: 1750e9aa5ddf
Revises: 2301fd695e50
Create Date: 2022-05-04 16:56:04.124401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1750e9aa5ddf'
down_revision = '2301fd695e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aiot_id', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=255), nullable=True),
    sa.Column('visas', sa.Text(), nullable=True),
    sa.Column('considerants', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aiot_id'], ['aiots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('arrete_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['arrete_id'], ['arretes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections_arretes_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrete_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrete_id'], ['arretes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispositions_abrogatoires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('nom_arrete', sa.String(length=255), nullable=False),
    sa.Column('articles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispositions_autres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispositions_autres')
    op.drop_table('dispositions_abrogatoires')
    op.drop_table('inspections_arretes_rel')
    op.drop_table('articles')
    op.drop_table('arretes')
    # ### end Alembic commands ###
