"""ajout champs controle

Revision ID: 202c16f06c2a
Revises: 09df091b5427
Create Date: 2022-05-02 16:48:37.932941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202c16f06c2a'
down_revision = '09df091b5427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insp_controles', sa.Column('nom', sa.String(length=255), nullable=True))
    op.drop_constraint(None, 'insp_controles', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles', 'inspections', ['insp_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'insp_controles', ['ctrl_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'demandes_exploitant', ['demande_exploitant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.create_foreign_key(None, 'inspections', 'aiots', ['aiot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inspections', 'users', ['approbateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['redacteur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['verificateur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.create_foreign_key(None, 'inspections', 'aiots', ['aiot_id'], ['id'])
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'insp_controles', ['ctrl_id'], ['id'])
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'demandes_exploitant', ['demande_exploitant_id'], ['id'])
    op.drop_constraint(None, 'insp_controles', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles', 'inspections', ['insp_id'], ['id'])
    op.drop_column('insp_controles', 'nom')
    # ### end Alembic commands ###
