"""ajout champs inspection

Revision ID: 2301fd695e50
Revises: 202c16f06c2a
Create Date: 2022-05-03 15:37:34.649407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2301fd695e50'
down_revision = '09df091b5427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insp_controles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(
            "fk_inspections_insp_controles", 
            'inspections', 
            ['insp_id'], ['id'], 
            ondelete='CASCADE'
        )
    
    with op.batch_alter_table('insp_controles_demandes_exploitant', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_insp_controles_demandes_exploitant_rel_demandes_exploitants", 'demandes_exploitant', ['demande_exploitant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key("fk_insp_controles_demandes_exploitant_rel_insp_controles", 'insp_controles', ['ctrl_id'], ['id'], ondelete='CASCADE')
    
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        pass
        #batch_op.add_column(sa.Column('synthese_proposition', sa.Text(), nullable=True))
        #batch_op.add_column(sa.Column('synthese_constats', sa.Text(), nullable=True))
        #batch_op.add_column(sa.Column('signataire_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspections_insp_controles', type_='foreignkey')
        batch_op.drop_column('inspections', 'signataire_id')
        batch_op.drop_column('inspections', 'synthese_constats')
        batch_op.drop_column('inspections', 'synthese_proposition')
    
    with op.batch_alter_table('insp_controles_demandes_exploitant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insp_controles_demandes_exploitant_rel_demandes_exploitants', type_='foreignkey')
        batch_op.drop_constraint('fk_insp_controles_demandes_exploitant_rel_insp_controles',  type_='foreignkey')

    with op.batch_alter_table('insp_controles', schema=None) as batch_op: 
        batch_op.drop_constraint('fk_inspections_insp_controles', type_='foreignkey')
        batch_op.drop_column('nom')
        
    # ### end Alembic commands ###
