"""ajout champs inspection

Revision ID: 2301fd695e50
Revises: 202c16f06c2a
Create Date: 2022-05-03 15:37:34.649407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2301fd695e50'
down_revision = '202c16f06c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insp_controles', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles', 'inspections', ['insp_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'demandes_exploitant', ['demande_exploitant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'insp_controles', ['ctrl_id'], ['id'], ondelete='CASCADE')
    op.add_column('inspections', sa.Column('synthese_proposition', sa.Text(), nullable=True))
    op.add_column('inspections', sa.Column('synthese_constats', sa.Text(), nullable=True))
    op.add_column('inspections', sa.Column('signataire_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.create_foreign_key(None, 'inspections', 'users', ['verificateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['redacteur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'aiots', ['aiot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inspections', 'users', ['signataire_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['approbateur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.create_foreign_key(None, 'inspections', 'aiots', ['aiot_id'], ['id'])
    op.drop_column('inspections', 'signataire_id')
    op.drop_column('inspections', 'synthese_constats')
    op.drop_column('inspections', 'synthese_proposition')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.drop_constraint(None, 'insp_controles_demandes_exploitant', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'demandes_exploitant', ['demande_exploitant_id'], ['id'])
    op.create_foreign_key(None, 'insp_controles_demandes_exploitant', 'insp_controles', ['ctrl_id'], ['id'])
    op.drop_constraint(None, 'insp_controles', type_='foreignkey')
    op.create_foreign_key(None, 'insp_controles', 'inspections', ['insp_id'], ['id'])
    # ### end Alembic commands ###
