"""ajout de champs inspections

Revision ID: 5ed69db40d55
Revises: ac6ad78d1708
Create Date: 2022-05-02 10:23:11.668614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed69db40d55'
down_revision = 'ac6ad78d1708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('redacteur_id', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('verificateur_id', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('approbateur_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inspections', 'users', ['verificateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['approbateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['redacteur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'approbateur_id')
    op.drop_column('inspections', 'verificateur_id')
    op.drop_column('inspections', 'redacteur_id')
    # ### end Alembic commands ###
