"""rev9

Revision ID: 60ac3c432689
Revises: 6a820c93002e
Create Date: 2022-05-17 14:26:29.953908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ac3c432689'
down_revision = '6a820c93002e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aiot_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('nature', sa.String(length=255), nullable=True),
    sa.Column('declare_le', sa.Date(), nullable=False),
    sa.Column('cessation_le', sa.Date(), nullable=False),
    sa.Column('parametres', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aiot_id'], ['aiots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regimes')
    # ### end Alembic commands ###
