"""rev8

Revision ID: 6a820c93002e
Revises: 6bdcd0838148
Create Date: 2022-05-05 10:31:53.047943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a820c93002e'
down_revision = '6bdcd0838148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arretes_inspections_rels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('arrete_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrete_id'], ['arretes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arretes_inspections_rels')
    # ### end Alembic commands ###
