"""rev7

Revision ID: 6bdcd0838148
Revises: 1750e9aa5ddf
Create Date: 2022-05-05 10:01:51.842785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdcd0838148'
down_revision = '1750e9aa5ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('insp_controles', 'controles')
    op.rename_table('insp_controles_demandes_exploitant', 'controles_demandes_exploitant_rels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('controles', 'insp_controles')
    op.rename_table('controles_demandes_exploitant_rels', 'insp_controles_demandes_exploitant')
    # ### end Alembic commands ###
