"""ajout champs AIOT

Revision ID: 95191bb12212
Revises: ac6ad78d1708
Create Date: 2022-05-02 14:21:03.642974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95191bb12212'
down_revision = '13fdf8662819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aiots', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('aiots', sa.Column('regime', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'inspections', 'users', ['approbateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['verificateur_id'], ['id'])
    op.create_foreign_key(None, 'inspections', 'users', ['redacteur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('aiots', 'regime')
    op.drop_column('aiots', 'email')
    # ### end Alembic commands ###
