"""ajout champs AIOT

Revision ID: 95191bb12212
Revises: ac6ad78d1708
Create Date: 2022-05-02 14:21:03.642974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95191bb12212'
down_revision = '13fdf8662819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aiots', schema=None) as batch_op:
        batch_op.add_column('aiots', sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column('aiots', sa.Column('regime', sa.String(length=255), nullable=True))
    
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_inspection_approbateur", 'users', ['approbateur_id'], ['id'])
        batch_op.create_foreign_key("fk_inspection_verificateur", 'users', ['verificateur_id'], ['id'])
        batch_op.create_foreign_key("fk_inspection_redacteur", 'users', ['redacteur_id'], ['id'])
        batch_op.create_foreign_key("fk_inspection_signataire", 'users', ['signataire_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_constraint(None, 'inspections', type_='foreignkey')
        batch_op.drop_constraint(None, 'inspections', type_='foreignkey')
        batch_op.drop_constraint(None, 'inspections', type_='foreignkey')

    with op.batch_alter_table('aiots', schema=None) as batch_op:
        batch_op.drop_column('aiots', 'regime')
        batch_op.drop_column('aiots', 'email')
    # ### end Alembic commands ###
