"""ajout de champs utilisateurs

Revision ID: ac6ad78d1708
Revises: 5fd9dcf670c2
Create Date: 2022-05-02 10:10:21.261147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6ad78d1708'
down_revision = '5fd9dcf670c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column('users', sa.Column('reference', sa.String(length=255), nullable=True))
        batch_op.add_column('users', sa.Column('fonction', sa.String(length=255), nullable=True))
        batch_op.add_column('users', sa.Column('nom', sa.String(length=255), nullable=True))
        batch_op.add_column('users', sa.Column('prenom', sa.String(length=255), nullable=True))
        batch_op.add_column('users', sa.Column('telephone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('users', 'telephone')
        batch_op.drop_column('users', 'prenom')
        batch_op.drop_column('users', 'nom')
        batch_op.drop_column('users', 'fonction')
        batch_op.drop_column('users', 'reference')
    # ### end Alembic commands ###
